# Generated by Django 5.0.2 on 2024-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_app', '0003_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
